In [1]:
#3a. Dataset Preparation, Training and Predicting the class with MLP.
import pandas as pd
from sklearn.preprocessing import LabelBinarizer
import numpy as np

In [3]:
col_names = ['slength', 'swidth', 'plength', 'pwidth', 'label']
# load dataset
iris = pd.read_csv("iris.csv", header=None, names=col_names)

iris.head()

slength  swidth  plength  pwidth        label
0      5.1     3.5      1.4     0.2  Iris-setosa
1      4.9     3.0      1.4     0.2  Iris-setosa
2      4.7     3.2      1.3     0.2  Iris-setosa
3      4.6     3.1      1.5     0.2  Iris-setosa
4      5.0     3.6      1.4     0.2  Iris-setosa

In [5]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

#Derivative of the sigmoid function
def sigmoid_prime(x):
    return sigmoid(x)*(1.0 - sigmoid(x))

In [6]:
labelbinarizer = LabelBinarizer()
make_encoded_results = labelbinarizer.fit_transform(iris['label'])
labelbinarizer.classes_
df_label_encoded = pd.DataFrame(make_encoded_results, columns=labelbinarizer.classes_)
# Viewing few rows of data
df_label_encoded.head()
iris.head()

iris_encoded = pd.concat([iris, df_label_encoded], axis=1, sort=False)
del iris_encoded['label']
iris_encoded.head()
rowcount=len(iris_encoded.index)
iris_encoded1 = iris_encoded.sample(frac = 1) 
#print(iris_encoded1)
iris_encoded=iris_encoded1.head(120)
iris_test=iris_encoded1.tail(30)
print(len(iris_encoded.index),len(iris_test.index))
#aaa=iris_encoded.iloc[1]
#aa[0]
#iris_encoded.iloc[1][2]
#len(iris_encoded.columns)

120 30


In [7]:
i_n=4
h_n=7
o_n=3

In [8]:
#print(iris_encoded)
#output_target=np.array(iris_encoded.iloc[:,-3:])
epochs=100
rowcount=len(iris_encoded.index)
print('row count ',rowcount)
wt_hidden=np.random.rand(h_n,i_n)*np.sqrt(2/i_n)
wt_output=np.random.rand(o_n,h_n)*np.sqrt(2/h_n)
#wt_hidden=np.random.rand(h_n,i_n)
#wt_output=np.random.rand(o_n,h_n)
print('input - hidden weights')
print(wt_hidden)
print('hidden-output weights')
print(wt_output)

bias_h=0.01
bias_o=0.01

in_h=np.zeros([h_n,1])
out_h=np.zeros([h_n,1])
out_o=np.zeros([o_n,])
in_o=np.zeros([o_n,])
output_labels=np.zeros([rowcount,o_n])
for i in range(epochs):
    output_labels=np.zeros([rowcount,o_n])
    correctly_classified=0;
    for j in range(rowcount):
        
        #forward pass input-hidden
        inp=iris_encoded.iloc[j,0:i_n]
        out=np.array(iris_encoded.iloc[j,-3:])
        #print(out)
        for k in range(h_n):
            inp_i=np.array(inp)
            wt_ih=np.array(wt_hidden[k])
            x=np.dot(wt_ih,inp_i)+bias_h
            out_h[k] = sigmoid(x)
            in_h[k]=x
        #print(hidden_output)
        #print(hidden_input)
        
        #forward pass hidden-output
        for k in range(o_n):
            out_h=np.array(out_h)
            wt_ho=np.array(wt_output[k])
            #print(out_h)
            #print('qqqqq')
            #print(wt_ho)
            x=np.dot(wt_ho,out_h)+bias_o
            out_o[k] = sigmoid(x)
            in_o[k]=x
            
        #print(out_o)
        #print(out)
        #print(y_output.shape,out.shape)
        #bias_h=bias_h-(0.1*bias_h)
        dif=np.subtract(out,out_o)
        dif_sq=np.square(dif)
        
        error=np.sum(dif_sq)
        
        error=error/2
        #print(error)
        
        labelind=np.argmax(out_o)
        output_labels[j][labelind]=1
        #print(output_labels[j],output_target[j])
        a=np.equal(output_labels[j],out)
        result = np.all(a)
        if(bool(result)):
            correctly_classified=correctly_classified+1
        #back propagation of error 
        for p in range(o_n):
            for q in range(h_n):
                derror=-(out[p]-out_o[p])*sigmoid_prime(in_o[p])*out_h[q]
                wt_output[p][q]=wt_output[p][q]-(0.3*derror)
                
        
        for p in range(h_n):
            for q in range(i_n):
                derror=0
                for r in range (o_n):
                    derror=derror+(-(out[r]-out_o[r])*sigmoid_prime(in_o[r])*wt_output[r][p])
                derror=derror*sigmoid_prime(in_h[p])*inp_i[q]
                wt_hidden[p][q]=wt_hidden[p][q]-(0.3*derror)
                #print(derror)
        bias_h=bias_h-(0.01*bias_h)
        bias_o=bias_h-(0.01*bias_o)
    print(correctly_classified)

print("after training the BPN")
print('input - hidden weights')
print(wt_hidden)
print('hidden-output weights')
print(wt_output)   
    

row count  120
input - hidden weights
[[0.33281237 0.08672334 0.18486531 0.44126736]
 [0.39815054 0.60554041 0.37030628 0.05950583]
 [0.34274631 0.01982366 0.52080763 0.01542342]
 [0.06667565 0.23647493 0.3765734  0.09700043]
 [0.33049577 0.17561991 0.44771369 0.00741888]
 [0.62795146 0.10140006 0.24175703 0.52580668]
 [0.53709593 0.4925039  0.49782676 0.23542774]]
hidden-output weights
[[0.2883684  0.40923308 0.15950101 0.13713258 0.20209453 0.44981944
  0.05747691]
 [0.52395485 0.26034056 0.19394313 0.4904631  0.5148228  0.03416807
  0.10980843]
 [0.08395259 0.51930088 0.46844232 0.08645093 0.25411179 0.12758934
  0.10323764]]
35
54
73
78
78
80
84
86
86
87
90
94
97
99
102
105
106
108
109
110
110
110
110
111
108
109
105
106
106
109
109
108
111
110
112
111
110
112
109
111
110
112
109
111
110
113
112
112
112
114
114
113
112
112
112
115
112
112
109
113
111
111
110
110
111
111
112
112
110
111
111
109
109
110
110
109
110
112
114
116
116
116
116
116
116
116
114
115
115
114
113
111
115
115
1

In [9]:
prediction_accuracy=correctly_classified/rowcount
print('prediction accuracy on training samples=',prediction_accuracy)

prediction accuracy on training samples= 0.9333333333333333


In [10]:
#test
#print(iris_encoded)
#output_target=np.array(iris_test.iloc[:,-3:])
rowcount=len(iris_test.index)
print('row count ',rowcount)

bias_h=0.1
bias_o=0.1

in_h=np.zeros([h_n,1])
out_h=np.zeros([h_n,1])
out_o=np.zeros([o_n,])
in_o=np.zeros([o_n,])
output_labels=np.zeros([rowcount,o_n])

correctly_classified=0;
for j in range(rowcount):
        
        #forward pass input-hidden
        inp=iris_encoded.iloc[j,0:i_n]
        out=np.array(iris_encoded.iloc[j,-3:])
        #print(out)
        for k in range(h_n):
            inp_i=np.array(inp)
            wt_ih=np.array(wt_hidden[k])
            x=np.dot(wt_ih,inp_i)+bias_h
            out_h[k] = sigmoid(x)
            in_h[k]=x
        
        
        #forward pass hidden-output
        for k in range(o_n):
            out_h=np.array(out_h)
            wt_ho=np.array(wt_output[k])
            x=np.dot(wt_ho,out_h)+bias_o
            out_o[k] = sigmoid(x)
            in_o[k]=x
            
        labelind=np.argmax(out_o)
        output_labels[j][labelind]=1
        #print(out_o,output_labels[j],out,output_target[j])
        #print(output_labels[j],output_target[j])
        a=np.equal(output_labels[j],out)
        result = np.all(a)
        if(bool(result)):
            correctly_classified=correctly_classified+1
print('prediction accuracy on testing samples=',correctly_classified,correctly_classified/rowcount)
    

row count  30
prediction accuracy on testing samples= 29 0.9666666666666667


In [11]:
#3b.Tune the learning rate,no.of epoch and even data preparation method to get an improved score on the dataset
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import metrics
#
# Import Keras modules
#
from keras import models
from keras import layers
from tensorflow.keras.utils import to_categorical
from sklearn.neural_network import MLPClassifier # neural network

In [12]:
iris = datasets.load_iris()

In [13]:
X = iris.data
y = iris.target

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=1)

In [15]:
train_labels = to_categorical(y_train)
test_labels = to_categorical(y_test)

In [16]:
clf = MLPClassifier(solver='adam', alpha=1e-5, hidden_layer_sizes=(3, 3), random_state=1)

In [17]:
clf.fit(X_train, y_train)

D:\Users\sf41\Anaconda3\envs\tensorflow_env\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(alpha=1e-05, hidden_layer_sizes=(3, 3), random_state=1)

In [18]:
prediction = clf.predict(X_test)
print(prediction)

[2 0 1 1 1 0 2 2 2 1 0 1 2 1 2 1 2 1 1 2 1 2 1 0 2 2 1 0 2 1]


In [19]:
print(y_test)

[2 0 1 0 0 0 2 2 2 1 0 1 2 1 2 0 2 1 1 2 1 1 0 0 2 2 0 0 1 1]


In [20]:
print('The accuracy of the Multi-layer Perceptron is:',metrics.accuracy_score(prediction,y_test))

The accuracy of the Multi-layer Perceptron is: 0.7666666666666667


In [21]:
network = models.Sequential()
network.add(layers.Dense(32, activation='relu', input_shape=(4,)))
network.add(layers.Dense(64, activation='relu'))
network.add(layers.Dense(128, activation='relu'))
network.add(layers.Dense(3, activation='softmax'))

In [22]:
network.compile(optimizer='sgd',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

In [23]:
network.fit(X_train, train_labels, epochs=20, batch_size=40)

Epoch 1/20
3/3 [==============================] - 1s 0s/step - loss: 1.0705 - accuracy: 0.4583
Epoch 2/20
3/3 [==============================] - 0s 3ms/step - loss: 1.0215 - accuracy: 0.2000
Epoch 3/20
3/3 [==============================] - 0s 1ms/step - loss: 0.9885 - accuracy: 0.4833
Epoch 4/20
3/3 [==============================] - 0s 3ms/step - loss: 0.9614 - accuracy: 0.5667
Epoch 5/20
3/3 [==============================] - 0s 1ms/step - loss: 0.9419 - accuracy: 0.6250
Epoch 6/20
3/3 [==============================] - 0s 3ms/step - loss: 0.9148 - accuracy: 0.5667
Epoch 7/20
3/3 [==============================] - 0s 1ms/step - loss: 0.8896 - accuracy: 0.6417
Epoch 8/20
3/3 [==============================] - 0s 2ms/step - loss: 0.8723 - accuracy: 0.6667
Epoch 9/20
3/3 [==============================] - 0s 1ms/step - loss: 0.8451 - accuracy: 0.6583
Epoch 10/20
3/3 [==============================] - 0s 2ms/step - loss: 0.8221 - accuracy: 0.6583
Epoch 11/20
3/3 [=======================

In [24]:
test_loss, test_acc = network.evaluate(X_test, test_labels)
#
# Print the test accuracy
#
print('Test Accuracy: ', test_acc, '\nTest Loss: ', test_loss)

1/1 [==============================] - 0s 144ms/step - loss: 0.6472 - accuracy: 0.6667
Test Accuracy:  0.6666666865348816 
Test Loss:  0.6471821069717407
